apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: mamadoudev/streamlit-app:v1
        name: streamlit-app
        ports:
        - containerPort: 8501
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
