name: MLOps CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Data-Processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing Script
        shell: bash
        run: |
          python src/data/run_processing.py   --input data/raw/house_data.csv   --output data/processed/cleaned_house_data.csv

      - name: Run feature engineering Script
        shell: bash
        run: |
          python src/features/engineer.py \
          --input data/processed/cleaned_house_data.csv \
          --output data/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl

      - name: Upload Processed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed/featured_house_data.csv

      - name: Upload preprocessor
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor
          path: models/trained/preprocessor.pkl

  Model-Training:
    needs: Data-Processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MLFlow Tracking Server
        shell: bash
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-tracking-server ghcr.io/mlflow/mlflow:latest \
          mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /tmp/mlruns

      - uses: actions/download-artifact@v4
        with:
          name: processed-data
          path: data/processed/

      - uses: actions/download-artifact@v4
        with:
          name: preprocessor
          path: models/trained/preprocessor.pkl
      
      - name: Run model training Script
        shell: bash
        run: |
          python src/models/train_model.py --config configs/model_config.yaml \
          --data data/processed/featured_house_data.csv --models-dir models \
          --mlflow-tracking-uri http://localhost:5555

      - name: Upload Processed data
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: models/trained/house_price_model.pkl

      - name: Upload preprocessor
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor
          path: models/trained/preprocessor.pkl
          
      - name: Cleanup MLFlow Tracking Server
        shell: bash
        run: |
          docker stop mlflow-tracking-server
          docker rm mlflow-tracking-server
          docker rmi ghcr.io/mlflow/mlflow:latest

  Docker-Build-and-Push:
    needs: Model-Training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v4
        with:
          name: model
          path: models/trained/house_price_model.pkl

      - uses: actions/download-artifact@v4
        with:
          name: preprocessor
          path: models/trained/preprocessor.pkl


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mamadoudev/fastapi:${{ env.sha_short }}
          context: "."
          file: "Dockerfile"